-d F:\EMB_pub\embedded\risc_v\ae350_soc\solution\1.1\Extended_AHB_Ethernet\ref_design\FPGA_RefDesign\Tang_MEGA_138K_Pro_Dock\ae350_ext_ethernet\impl\gwsynthesis\ae350_ext_ethernet.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst F:\EMB_pub\embedded\risc_v\ae350_soc\solution\1.1\Extended_AHB_Ethernet\ref_design\FPGA_RefDesign\Tang_MEGA_138K_Pro_Dock\ae350_ext_ethernet\src\ae350_ext_ethernet.cst
-cfg F:\EMB_pub\embedded\risc_v\ae350_soc\solution\1.1\Extended_AHB_Ethernet\ref_design\FPGA_RefDesign\Tang_MEGA_138K_Pro_Dock\ae350_ext_ethernet\impl\pnr\device.cfg
-sdc F:\EMB_pub\embedded\risc_v\ae350_soc\solution\1.1\Extended_AHB_Ethernet\ref_design\FPGA_RefDesign\Tang_MEGA_138K_Pro_Dock\ae350_ext_ethernet\src\ae350_ext_ethernet.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-place_option 1
-route_option 2
-correct_hold 1
-route_maxfan 23
